// tslint:disable:max-line-length

export const literals = {
  ca_ES: {
    signIn: 'iniciar sessió',
    signOut: 'tancar sessió',
    dontYouHaveAccount: 'no tens usuari?',
    doYouHaveAVerificationCode: 'tens un codi de verificació?',
    introduceVerificationCode: 'introduir codi de verificació',
    verificate: 'verifica',
    signUp: 'registrar-se',
    invalidVerificationCode: 'Codi de verificació incorrecte',
    userNotFound: 'l\'email introduït no està enregistrar',
    invalidSignInParams: 'l\'email i/o la contrasenya introduïdes no són correctes',
    next: 'següent',
    save: 'guardar',
    send: 'enviar',
    name: 'nom',
    email: 'e-mail',
    code: 'codi',
    lastnames: 'cognoms',
    municipality: 'municipi',
    telephone: 'telèfon',
    repeatPassword: 'repeteix la contrasenya',
    password: 'contrasenya',
    nationalIdentityDocument: 'NIF o NIE',
    verificationCode: 'codi de verificació',
    checkYourEmail: 'revisa el teu e-mail.',
    verificationCodeSentToYourEmail: 't\'hem enviat un correu electrònic amb un codi de verificació.',
    whoAreYou: 'qui ets?',
    userInfo: 'dades d\'usuari',
    contactInfo: 'dades de contacte',
    emailUsed: 'l\'email introduït ja està enregistrat a AMB. Fes servir un altre o pots iniciar sessió',
    here: 'aquí',
    invalidEmail: 'l\'e-mail introduït no és vàlid',
    chooseLine: 'selecciona la línia',
    chooseRoute: 'selecciona la teva ruta',
    chooseOrigin: 'selecciona l\'origen',
    chooseOriginBusStop: 'selecciona l\'estació d\'origen',
    chooseSeats: 'selecciona places',
    originBusStop: 'estació d\'origen',
    destinationBusStop: 'estació de desti',
    chooseDestinationBusStop: 'selecciona l\'estació de destí',
    continue: 'continuar',
    chooseDate: 'selecciona la data',
    chooseSchedule: 'selecciona horari',
    routeDetails: 'detalls de la ruta',
    reserve: 'reservar',
    daily: 'diariament',
    cancel: 'cancel·lar',
    weekly: 'setmanalment',
    never: 'mai',
    repeat: 'repetir',
    twoLetterMonday: 'Dl',
    twoLetterTuesday: 'Dt',
    twoLetterWednesday: 'Dc',
    twoLetterThursday: 'Dj',
    twoLetterFriday: 'Dv',
    twoLetterSaturday: 'Ds',
    twoLetterSunday: 'Dg',
    threeLetterMonday: 'Dll',
    threeLetterTuesday: 'Dmt',
    threeLetterWednesday: 'Dim',
    threeLetterThursday: 'Dij',
    threeLetterFriday: 'Div',
    threeLetterSaturday: 'Dss',
    threeLetterSunday: 'Diu',
    account: 'compte',
    reservations: 'reserves',
    penalties: 'incidències',
    language: 'idioma',
    changeLanguage: 'canviar l\'idioma',
    information: 'informació',
    towards: 'Cap a',
    newReservation: 'nova reserva',
    newPassword: 'nova constrasenya',
    pastReservations: 'reserves passades',
    nextReservations: 'pròximes reserves',
    great: 'fantàstic',
    noPenalties: 'no tens cap falta d\'assistència',
    expiresIn: 'expira en',
    days: 'dies',
    noReservations: 'no tens cap reserva',
    canceledReservation: 'reserva cancel·lada',
    dueToProblemsCanceled: 'a causa de problemes en la línia, l\'autobús no passarà per la teva parada a l\'hora sol·licitada. Sentim les molèsties.',
    startUsing: 'fes click al botó de nova reserva per començar a fer ús del servei',
    forgottenPassword: 'no recordes la contrasenya?',
    emailNotFound: 'l\'email introduït no està registrat',
    nifNotFound: 'el NIF introduït no està registrat',
    invalidRecoverPasswordCode: 'codi de recuperació de contrasenya no vàlid',
    writeYourEmail: 'escriu el teu email',
    writeYourNif: 'escriu el teu NIF',
    willSendVerificationCode: 't\'enviarem un codi de verificació per restablir la teva contrasenya',
    restoreYourPassword: 'reestableix la teva contrasenya',
    setYourPassword: 'estableix la teva contrasenya',
    passwordNotValid: 'la contrasenya introduïda no és vàlida',
    changePassword: 'canviar la contrasenya',
    createAccount: 'crear compte',
    dropOutFromService: 'donar-se de baixa del servei',
    catalan: 'català',
    spanish: 'espanyol',
    service: 'servei',
    profile: 'perfil',
    personalInfo: 'dades personals',
    changePasswordSpecification: 'assegurat que la nova contrasenya contingui com a mínim un número, una lletra minúscula, una majúscula i un caràcter especial',
    changePasswordInvalidPasswordError: 'contrasenya incorrecta',
    changePasswordLimitExceededError: 'límit d\'intents excedit, intenta-ho més tard',
    forgotPasswordLimitExceededError: 'límit d\'intents excedit, intenta-ho més tard',
    sadToSeeYouGo: 'lamentem que tinguis pensat donar-te de baixa del sistema. Si us plau, indiqueu el motiu pel qual et vols marxar',
    chooseAReason: 'tria un motiu',
    unsubscribe: 'donar de baixa',
    confirmUnsubscribe: 'confirmar baixa',
    atYourService: 'estem a la teva disposició a través de',
    attentionSchedule: 'horari d\'atenció al client: de dilluns a divendres de 8:00h a 20:00h',
    ambMovilityWeb: 'web de AMB Mobilitat',
    confirmated: 'confirmat',
    nowBackToSignIn: 'ara pots tornar i fer login',
    goBack: 'tornar',
    dismissNotification: 'tancar',
    acceptNotification: 'veure la reserva',
    requestNewSignUpVerificationCode: 'sol·licitar un nou codi',
    emailAlreadyConfirmated: 'l\'email introduït ja està verificat',
    emailNotRegistered: 'l\'email introduït no està enregistrat',
    formatNotValid: 'format no valid',
    day1: 'Dilluns',
    day2: 'Dimarts',
    day3: 'Dimecres',
    day4: 'Dijous',
    day5: 'Divendres',
    day6: 'Dissabte',
    day7: 'Diumenge',
    month0: 'Gener',
    month1: 'Febrer',
    month2: 'Març',
    month3: 'Abril',
    month4: 'Maig',
    month5: 'Juny',
    month6: 'Juliol',
    month7: 'Agost',
    month8: 'Septembre',
    month9: 'Octubre',
    month10: 'Novembre',
    month11: 'Desembre',
    monthShort0: 'Gen.',
    monthShort1: 'Febr.',
    monthShort2: 'Març',
    monthShort3: 'Abr.',
    monthShort4: 'Maig',
    monthShort5: 'Juny',
    monthShort6: 'Jul.',
    monthShort7: 'Ag.',
    monthShort8: 'Set.',
    monthShort9: 'Oct.',
    monthShort10: 'Nov.',
    monthShort11: 'Des.',
    period1: 'Tots els',
    period2: '(excepte festius i caps de setmana) durant un mes.',
    and: 'i',
    stops: 'parades',
    noSchedulesFound: 'no hi han horaris disponibles per la data seleccionada',
    delete: 'eliminar',
    edit: 'editar',
    cancelReservation: 'cancel·lar reserva',
    chooseMunicipality: 'selecciona un municipi',
    standardSeats: 'places estàndard',
    prmSeats: 'places amb cadira de rodes',
    seatsLeft: 'places disponibles',
    noSeatsAvailable: 'no hi ha places disponibles',
    noPrmSeatsAvailable: 'no hi ha places amb cadira de rodes disponibles',
    seatsReserved: 'places reservades',
    nifUsed: 'el NIF introduït ja està enregistrat. Fes servir un altre.',
    nifNotUsed: 'el NIF introduït no està enregistrat. Fes servir un altre.',
    iDontUseIt: 'no ho faig servir',
    noReason: 'cap motiu',
    reservationsBlocked: 'reserves bloquejades',
    tooManyReservations: 'has acumulat massa faltes d\'assistència',
    dontForgetReservations: 'no oblidis assistir a les teves reserves!',
    userExpired: 'El compte d\'usuari ha caducat, ha de ser restablit per un administrador',
    howToRepeatReservation: 'Com repetir la meva reserva',
    explaningHowToRepeatReservation: 'Selecciona l\'opció "Repetir" a la icona d\'opcions de la pantalla de detall d\'una reserva',
    goToMyReservation: 'anar a la meva reserva',
    quit: 'sortir',
    pickCalendar: 'selecciona al calendari els dies que vols que es repeteixi la reserva',
    today: 'avui',
    tomorrow: 'demà',
    optional: 'opcional',
    passwordPolicy: 'la contrasenya ha de tenir almenys vuit caràcters, una lletra minúscula, una lletra majúscula, un número i un caràcter especial',
    thanksForUsing: 'gràcies per utilitzar el servei de bus a la demanda. Si us plau, introdueix les teves dades.',
    contact: 'contacte',
    legalNotice: 'avís legal',
    ago: 'fa',
    unhandledError: 's\'ha produït un error inesperat. Si l\'error persisteix, si us plau posi\'s en contacte',
    reservationSaved: 'reserva creada satisfactòriament',
    reservationNotSaved: 's\'ha produït un error, reserva no creada',
    reservationUpdated: 'reserva modificada satisfactòriament',
    reservationNotUpdated: 's\'ha produït un error, reserva no modificada',
    reservationDeleted: 'reserva eliminada correctament',
    reservationNotDeleted: 's\'ha produït un error, reserva no eliminada',
    reservationRepeated: 'reserva repetida correctament',
    reservationNotRepeated: 's\'ha produït un error, reserva no repetida',
    profileUpdated: 'perfil modificat satisfactòriament',
    profileNotUpdated: 's\'ha produït un error, perfil no modificat',
    languageUpdated: 'idioma modificat satisfactòriament',
    languageNotUpdated: 's\'ha produït un error, idioma no modificat',
    sureSignOut: 'estàs segur que vols tancar sessió?',
    sureExit: 'estàs segur que vols tancar l\'aplicació?',
    yes: 'si',
    chooseBusSchedule: 'Tria l\'hora de sortida del teu bus.',
    busScheduleAlert: 'T\'avisarem amb una notificació quan quedin aprox. 5 minuts per l\'arribada del bus a la teva parada.',
    serviceInformation: 'Informació del servei',
    contactForm: 'formulari de contacte',
    noConnection: 'Sense conexió',
    UsernameExistsException: 'L\'usuari ja existeix',
    InvalidParameterException: 'Paràmetres no vàlids',
    LimitExceededException: 'Límit d\'intents excedit, intenta-ho més tard',
    UserNotFoundException: 'L\'usuari no existeix, intenta-ho amb un altre nom',
    NotAuthorizedException: 'No tens permisos per realitzar aquesta acció',
    CodeMismatchException: 'El codi introduït no coincideix'
  },
  es_ES: {
    signIn: 'iniciar sesión',
    signOut: 'cerrar sesión',
    dontYouHaveAccount: '¿no tienes usuario?',
    doYouHaveAVerificationCode: '¿tienes un código de verificación?',
    introduceVerificationCode: 'introducir codigo de verificación',
    verificate: 'verifica',
    signUp: 'registrarse',
    invalidVerificationCode: 'Codigo de verificación incorrecto',
    userNotFound: 'el e-mail introducido no está registrado',
    invalidSignInParams: 'el e-mail o contraseña introducida no es correcta',
    next: 'siguiente',
    save: 'guardar',
    send: 'enviar',
    name: 'nombre',
    email: 'e-mail',
    code: 'código',
    lastnames: 'apellido',
    municipality: 'municipio',
    telephone: 'teléfono',
    repeatPassword: 'repite la contraseña',
    password: 'contraseña',
    nationalIdentityDocument: 'NIF o NIE',
    verificationCode: 'código de verificación',
    checkYourEmail: 'revisa tu e-mail.',
    verificationCodeSentToYourEmail: 'te hemos enviado un correo electrónico con un código de verificación',
    whoAreYou: '¿quien eres?',
    userInfo: 'datos de usuario',
    contactInfo: 'datos de contacto',
    emailUsed: 'El e-mail introducido ya esta registrado en AMB. Usa otro o puedes iniciar sesión',
    here: 'aquí',
    invalidEmail: 'el e-mail introducido no es valido',
    chooseLine: 'selecciona la linea',
    chooseRoute: 'selecciona tu ruta',
    chooseOrigin: 'selecciona el origen',
    chooseOriginBusStop: 'selecciona la estación de origen',
    chooseSeats: 'selecciona plazas',
    originBusStop: 'estación de origen',
    destinationBusStop: 'estación de destino',
    chooseDestinationBusStop: 'selecciona la estación de destino',
    continue: 'continuar',
    chooseDate: 'selecciona la fecha',
    chooseSchedule: 'selecciona el horario',
    routeDetails: 'detalles de la ruta',
    reserve: 'reservar',
    daily: 'diariamente',
    cancel: 'cancelar',
    weekly: 'semanalmente',
    never: 'nunca',
    repeat: 'repetir',
    twoLetterMonday: 'Lu',
    twoLetterTuesday: 'Ma',
    twoLetterWednesday: 'Mi',
    twoLetterThursday: 'Ju',
    twoLetterFriday: 'Vi',
    twoLetterSaturday: 'Sa',
    twoLetterSunday: 'Do',
    threeLetterMonday: 'Lun',
    threeLetterTuesday: 'Mar',
    threeLetterWednesday: 'Mie',
    threeLetterThursday: 'Jue',
    threeLetterFriday: 'Vie',
    threeLetterSaturday: 'Sab',
    threeLetterSunday: 'Dom',
    account: 'cuenta',
    reservations: 'reservas',
    penalties: 'incidencias',
    language: 'idioma',
    changeLanguage: 'cambiar el idioma',
    information: 'información',
    towards: 'Hacia',
    newReservation: 'nueva reserva',
    newPassword: 'nueva contraseña',
    pastReservations: 'reservas pasadas',
    nextReservations: 'próximas reservas',
    great: 'fantástico',
    noPenalties: 'no tienes ninguna falta de asistencia',
    expiresIn: 'expira en',
    days: 'dias',
    noReservations: 'no tienes ninguna reserva',
    canceledReservation: 'reserva cancelada',
    dueToProblemsCanceled: 'debido a problemas en la línea, el autobús no pasará por tu parada a la hora solicitada. Sentimos las molestias.',
    startUsing: 'haz click en el botón de nueva reserva para comenzar a hacer uso del servicio',
    forgottenPassword: '¿has olvidado la contraseña?',
    emailNotFound: 'el e-email introducido no esta registrado',
    nifNotFound: 'el NIF introducido no esta registrado',
    invalidRecoverPasswordCode: 'código de recuperación de contraseña no valido',
    writeYourEmail: 'escribe tu e-mail',
    writeYourNif: 'escribe tu NIF',
    willSendVerificationCode: 'te enviaremos un código de verificación para restablecer tu contraseña',
    restoreYourPassword: 'restablece tu contraseña',
    setYourPassword: 'establece tu contraseña',
    passwordNotValid: 'la contraseña introducida no es valida',
    changePassword: 'cambiar la contraseña',
    createAccount: 'crear cuenta',
    dropOutFromService: 'darse de baja del servicio',
    catalan: 'catalán',
    spanish: 'español',
    service: 'servicio',
    profile: 'perfil',
    personalInfo: 'datos personales',
    changePasswordSpecification: 'asegúrate de que la nueva contraseña contenga como mínimo un número, una letra minúscula, una mayúscula y un carácter especial',
    changePasswordInvalidPasswordError: 'contraseña incorrecta',
    changePasswordLimitExceededError: 'limite de intentos excedido, intentalo más tarde',
    forgotPasswordLimitExceededError: 'limite de intentos excedido, intentalo más tarde',
    sadToSeeYouGo: 'lamentamos que tengas pensado darte de baja del sistema. Por favor, indícanos el motivo por el cual te quieres marchar',
    chooseAReason: 'elige un motivo',
    unsubscribe: 'dar de baja',
    confirmUnsubscribe: 'confirmar baja',
    atYourService: 'estamos a tu disposición a través de',
    attentionSchedule: 'horario de atención al cliente: de lunes a viernes de 8:00h a 20:00h',
    ambMovilityWeb: 'web de AMB Mobilitat',
    confirmated: 'confirmado',
    nowBackToSignIn: 'ahora puedes volver y identificarte',
    goBack: 'volver',
    dismissNotification: 'cerrar',
    acceptNotification: 'ver la reserva',
    requestNewSignUpVerificationCode: 'solicitar un nuevo código',
    emailAlreadyConfirmated: 'el e-mail introducido ya esta verificado',
    emailNotRegistered: 'el e-mail introducido no esta registrado',
    formatNotValid: 'formato no valido',
    day1: 'Lunes',
    day2: 'Martes',
    day3: 'Miércoles',
    day4: 'Jueves',
    day5: 'Viernes',
    day6: 'Sábado',
    day7: 'Domingo',
    month0: 'Enero',
    month1: 'Febrero',
    month2: 'Marzo',
    month3: 'Abril',
    month4: 'Mayo',
    month5: 'Junio',
    month6: 'Julio',
    month7: 'Agosto',
    month8: 'Septiembre',
    month9: 'Octubre',
    month10: 'Noviembre',
    month11: 'Diciembre',
    monthShort0: 'En.',
    monthShort1: 'Febr.',
    monthShort2: 'Mzo.',
    monthShort3: 'Abr.',
    monthShort4: 'My.',
    monthShort5: 'Jun.',
    monthShort6: 'Jul.',
    monthShort7: 'Agto.',
    monthShort8: 'Sept.',
    monthShort9: 'Oct.',
    monthShort10: 'Nov.',
    monthShort11: 'Dic.',
    period1: 'Todos los',
    period2: '(excepto festivos y fines de semana) durante un mes.',
    and: 'y',
    stops: 'paradas',
    noSchedulesFound: 'no hi han horaris disponibles per la data seleccionada',
    delete: 'eliminar',
    edit: 'editar',
    cancelReservation: 'cancelar reserva',
    chooseMunicipality: 'selecciona un municipio',
    standardSeats: 'plazas estándard',
    prmSeats: 'plazas con silla de ruedas',
    seatsLeft: 'plazas disponibles',
    noSeatsAvailable: 'no hay plazas disponibles',
    noPrmSeatsAvailable: 'no hay plazas con silla de ruedas disponibles',
    seatsReserved: 'plazas reservadas',
    nifUsed: 'el NIF introducido ya está registrado. Usa otro.',
    nifNotUsed: 'el NIF introducido no está registrado. Usa otro.',
    iDontUseIt: 'no lo uso',
    noReason: 'sin razón',
    reservationsBlocked: 'reservas bloqueadas',
    tooManyReservations: 'has acumulado demasiadas faltas de asistencia',
    dontForgetReservations: '¡No olvides asistir a tus reservas!',
    userExpired: 'la cuenta de usuario ha caducado, debe ser restablecida por un administrador',
    howToRepeatReservation: 'cómo repetir mi reserva',
    explaningHowToRepeatReservation: 'selecciona la opción “Repetir” en el icono de opciones de la pantalla de detalle de una reserva',
    goToMyReservation: 'ir a mi reserva',
    quit: 'salir',
    pickCalendar: 'selecciona en el calendario los días que quieres que se repita la reserva',
    today: 'hoy',
    tomorrow: 'mañana',
    optional: 'opcional',
    passwordPolicy: 'la contraseña debe tener al menos ocho caracteres, una letra minúscula, una letra mayúscula, un número y un carácter especial',
    thanksForUsing: 'gracias por utilizar el servicio de bus a la demanda. Por favor, introduce tus datos.',
    contact: 'contacto',
    legalNotice: 'aviso legal',
    ago: 'hace',
    unhandledError: 'se ha producido un error inesperado. Si el error persiste, por favor póngase en contacto',
    reservationSaved: 'reserva creada satisfactoriamente',
    reservationNotSaved: 'se ha producido un error, reserva no creada',
    reservationUpdated: 'reserva modificada satisfactoriamente',
    reservationNotUpdated: 'se ha producido un error, reserva no modificada',
    reservationDeleted: 'reserva eliminada satisfactoriamente',
    reservationNotDeleted: 'se ha producido un error, reserva no eliminada',
    reservationRepeated: 'reserva repetida satisfactoriamente',
    reservationNotRepeated: 'se ha producido un error, reserva no repetida',
    profileUpdated: 'perfil modificado satisfactoriamente',
    profileNotUpdated: 'se ha producido un error, perfil no modificado',
    languageUpdated: 'idioma modificado satisfactoriamente',
    languageNotUpdated: 'se ha producido un error, idioma no modificado',
    sureSignOut: '¿estás seguro que quieres cerrar sesión?',
    sureExit: '¿estás seguro que quieres cerrar la aplicación?',
    yes: 'sí',
    chooseBusSchedule: 'Elige la hora de salida de tu bus.',
    busScheduleAlert: 'Te avisaremos con una notificación cuando queden aprox. 5 minutos para la llegada del bus a tu parada.',
    serviceInformation: 'Información del servicio',
    contactForm: 'formulario de contacto',
    noConnection: 'Sin conexión',
    UsernameExistsException: 'El usuario ya existe',
    InvalidParameterException: 'Parametros inválidos',
    LimitExceededException: 'limite de intentos excedido, intentalo más tarde',
    UserNotFoundException: 'El usuario no existe, intentalo con otro nombre',
    NotAuthorizedException: 'No tienes permisos para realizar esta acción',
    CodeMismatchException: 'El código ingresado no coincide'
  }
}

export const calendarLiterals = {
  ca_ES : {
    monthNames: [
      literals.ca_ES.month0,
      literals.ca_ES.month1,
      literals.ca_ES.month2,
      literals.ca_ES.month3,
      literals.ca_ES.month4,
      literals.ca_ES.month5,
      literals.ca_ES.month6,
      literals.ca_ES.month7,
      literals.ca_ES.month8,
      literals.ca_ES.month9,
      literals.ca_ES.month10,
      literals.ca_ES.month11
    ],
    monthNamesShort: [
      literals.ca_ES.monthShort0,
      literals.ca_ES.monthShort1,
      literals.ca_ES.monthShort2,
      literals.ca_ES.monthShort3,
      literals.ca_ES.monthShort4,
      literals.ca_ES.monthShort5,
      literals.ca_ES.monthShort6,
      literals.ca_ES.monthShort7,
      literals.ca_ES.monthShort8,
      literals.ca_ES.monthShort9,
      literals.ca_ES.monthShort10,
      literals.ca_ES.monthShort11
    ],
    dayNames: [
      literals.ca_ES.day1,
      literals.ca_ES.day2,
      literals.ca_ES.day3,
      literals.ca_ES.day4,
      literals.ca_ES.day5,
      literals.ca_ES.day6,
      literals.ca_ES.day7
    ],
    dayNamesShort: [
      literals.ca_ES.threeLetterSunday,
      literals.ca_ES.threeLetterMonday,
      literals.ca_ES.threeLetterTuesday,
      literals.ca_ES.threeLetterWednesday,
      literals.ca_ES.threeLetterThursday,
      literals.ca_ES.threeLetterFriday,
      literals.ca_ES.threeLetterSaturday
    ]
  },

  // tslint:disable-next-line:no-string-literal
  es_ES : {
    monthNames: [
      literals.es_ES.month0,
      literals.es_ES.month1,
      literals.es_ES.month2,
      literals.es_ES.month3,
      literals.es_ES.month4,
      literals.es_ES.month5,
      literals.es_ES.month6,
      literals.es_ES.month7,
      literals.es_ES.month8,
      literals.es_ES.month9,
      literals.es_ES.month10,
      literals.es_ES.month11
    ],
    monthNamesShort: [
      literals.es_ES.monthShort0,
      literals.es_ES.monthShort1,
      literals.es_ES.monthShort2,
      literals.es_ES.monthShort3,
      literals.es_ES.monthShort4,
      literals.es_ES.monthShort5,
      literals.es_ES.monthShort6,
      literals.es_ES.monthShort7,
      literals.es_ES.monthShort8,
      literals.es_ES.monthShort9,
      literals.es_ES.monthShort10,
      literals.es_ES.monthShort11
    ],
    dayNames: [
      literals.es_ES.day1,
      literals.es_ES.day2,
      literals.es_ES.day3,
      literals.es_ES.day4,
      literals.es_ES.day5,
      literals.es_ES.day6,
      literals.es_ES.day7
    ],
    dayNamesShort: [
      literals.es_ES.threeLetterSunday,
      literals.es_ES.threeLetterMonday,
      literals.es_ES.threeLetterTuesday,
      literals.es_ES.threeLetterWednesday,
      literals.es_ES.threeLetterThursday,
      literals.es_ES.threeLetterFriday,
      literals.es_ES.threeLetterSaturday
    ]
  }
}
